### ISSUE TITLE
 How to deploy WASM app in *.wasm format?

### ISSUE THREAD

**Issue by VR-Architect** [Acurast/acurast-example-apps#2]
Could someone please make a quick example on how to deploy a *.wasm file? I create Blazor webassembly applications and would like to see if I can take the resulting wasm file and deploy to Acurast or not?

Thanks in advanced

**Comment by AndreasGassmann** [comment]
Hi. I'm sorry I missed your question.

There is an example with a .wasm file in this repository: https://github.com/Acurast/acurast-example-apps/tree/main/apps/app-wasm/src

Feel free to re-open this issue if you have any issues with it!
